version: '3.8'

services:
  php_mars_rover_mission:
    build:
      context: etc/infrastructure/php
      dockerfile: Dockerfile
    container_name: php_mars_rover_mission
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - 9001:9003 #9003:9000 fa desapareixer missatges d'error pero llavors no furula xdebug
    environment:
      XDEBUG_MODE: debug

  nginx_mars_rover_mission:
    image: nginx:latest
    container_name: nginx_mars_rover_mission
    ports:
      - 8000:80
    volumes:
      - ./etc/infrastructure/nginx/conf.d:/etc/nginx/conf.d
      - ./apps/MarsRoverMissionApi/public/:/app/apps/MarsRoverMissionApi/public
    depends_on:
      - php_mars_rover_mission

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
    container_name: elasticsearch
    ports: [ '9200:9200' ]
    environment:
      - "ELASTIC_PASSWORD=elastic"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "discovery.type=single-node"
      - "TAKE_FILE_OWNERSHIP=1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - './var/elasticsearch:/usr/share/elasticsearch/data'

  logstash:
    image: docker.elastic.co/logstash/logstash:${ELK_VERSION}
    container_name: logstash
    environment:
      - "ELASTIC_PASSWORD=elastic"
    ports: [ '9600:9600' ]
    depends_on:
      - elasticsearch
    volumes:
      - './etc/infrastructure/logstash/pipeline:/usr/share/logstash/pipeline'
      - './apps/MarsRoverMissionApi/var/log:/logs'

  filebeat:
    image: docker.elastic.co/beats/filebeat:${ELK_VERSION}
    container_name: filebeat
    environment:
      - "ELASTIC_PASSWORD=elastic"
    ports: [ '5044:5044' ]
    depends_on:
      - logstash
    user: root
    volumes:
      - './apps/MarsRoverMissionApi/var/log/:/var/lib/docker/containers/logs:ro'
      - './etc/infrastructure/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml'
    command: [ "--strict.perms=false" ]

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELK_VERSION}
    container_name: kibana
    environment:
      - "ELASTIC_PASSWORD=elastic"
    ports: [ '5601:5601' ]
    depends_on:
      - elasticsearch
