parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    MarsRoverMissionApi\:
        resource: '../src/'
    MarsRoverMission\:
        resource: '../../../src/MarsRoverMission/'
    Shared\:
        resource: '../../../src/Shared/'

    Shared\Infrastructure\Symfony\Bus\Query\SymfonyQueryBus:
        arguments:
            $bus: '@query.bus'

    _instanceof:
        Shared\Domain\Bus\Command\CommandHandler:
            tags:
                - { name: messenger.message_handler, bus: command.bus }
        Shared\Domain\Bus\Query\QueryHandler:
            tags:
                - { name: messenger.message_handler, bus: query.bus }

framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus:
            query.bus:

    error_controller: MarsRoverMissionApi\Controller\ErrorController
