# Create a map
POST localhost:8000/map/generate
Content-Type: application/json

{
  "width": 10,
  "height": 10
}

###
# Get a map
GET localhost:8000/map
Content-Type: application/json

###
# Set Rover position
POST localhost:8000/rover/position
Content-Type: application/json

{
  "x": 0,
  "y": 0,
  "facing-direction": "N"
}

###
# Move Rover
PUT localhost:8000/rover/move
Content-Type: application/json

{
  "instructions": "FF"
}
